const ARTIFICIAL_EXACT_KEYS = new Set([
  "aiconfig",
  "airesponse",
  "categorymatch",
  "collectionrepair",
  "collectionsourceimages",
  "detailfetch",
  "featurefill",
  "featurefillmode",
  "imagegeneration",
  "imagegenerationconfig",
  "imageworkflow",
  "pettoybatch",
  "processing",
  "processingstate",
  "promptaudit",
  "quickmode",
  "skufeaturedrafts",
  "skufeaturedraftsupdatedat",
  "skuselection",
  "selectedvariant",
  "stageaiprompts",
  "workflowimages",
]);

const COLLECTOR_METADATA_KEYS = new Set([
  "capturemode",
  "collectedat",
  "fetched",
  "fetcherror",
  "fetchstatus",
  "repairedat",
]);

const ARTIFICIAL_METADATA_KEYS = new Set([
  "aspectratio",
  "capturemode",
  "fetched",
  "fetcherror",
  "fetchstatus",
  "model",
  "modelid",
  "providerid",
  "providername",
  "requestid",
  "runid",
  "taskid",
  "usereference",
  "workerid",
]);

const COLLECTOR_INJECTED_KEYS = new Set([
  "aiconfig",
  "airesponse",
  "categorymatch",
  "collectionrepair",
  "collectionsourceimages",
  "detailfetch",
  "featurefill",
  "featurefillmode",
  "imagegeneration",
  "imagegenerationconfig",
  "imageworkflow",
  "pettoybatch",
  "processing",
  "processingstate",
  "promptaudit",
  "quickmode",
  "skufeaturedrafts",
  "skufeaturedraftsupdatedat",
  "skuselection",
  "selectedvariant",
  "stageaiprompts",
  "workflowimages",
]);

function normalizedKey(key: string) {
  return key.replace(/[^a-zA-Z0-9]/g, "").toLowerCase();
}

function isArtificialProductJsonKey(key: string) {
  const normalized = normalizedKey(key);
  return (
    ARTIFICIAL_EXACT_KEYS.has(normalized) ||
    ARTIFICIAL_METADATA_KEYS.has(normalized) ||
    normalized.includes("prompt") ||
    normalized.startsWith("generated") ||
    normalized.startsWith("translated") ||
    normalized.startsWith("autogenerated") ||
    normalized.startsWith("autotranslated") ||
    normalized.endsWith("workflowstatus") ||
    normalized.endsWith("promptconfig") ||
    /(?:created|updated|captured|collected|queued|started|finished|completed)at$/.test(
      normalized,
    )
  );
}

function cleanValue(value: unknown): unknown {
  if (Array.isArray(value)) {
    const cleaned = value
      .map(cleanValue)
      .filter((entry) => entry !== undefined);
    return cleaned.length ? cleaned : undefined;
  }
  if (value && typeof value === "object") {
    const cleaned = Object.entries(value as Record<string, unknown>)
      .filter(([key]) => !isArtificialProductJsonKey(key))
      .flatMap(([key, entry]) => {
        const next = cleanValue(entry);
        return next === undefined ? [] : [[key, next] as const];
      });
    return cleaned.length ? Object.fromEntries(cleaned) : undefined;
  }
  if (value === null || value === undefined || value === "") return undefined;
  return value;
}

function cleanCollectedValue(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(cleanCollectedValue);
  }
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>)
        .filter(([key]) => {
          const normalized = normalizedKey(key);
          return (
            !COLLECTOR_INJECTED_KEYS.has(normalized) &&
            !COLLECTOR_METADATA_KEYS.has(normalized) &&
            !normalized.includes("prompt")
          );
        })
        .map(([key, entry]) => [key, cleanCollectedValue(entry)]),
    );
  }
  return value;
}

/**
 * 采集边界使用：只移除程序曾经注入的提示词、AI 中间结果和工作流状态，
 * 不删减 1688 本身抓到的空值、时间、图片或商品字段。
 */
export function sanitizeCollectedProductJson(
  product: Record<string, unknown>,
): Record<string, unknown> {
  return cleanCollectedValue(product) as Record<string, unknown>;
}

/**
 * 构建发送给商品属性 Skill 的纯商品事实 JSON。
 * UI 状态、提示词、模型配置、加工进度和 AI 中间产物全部留在本地。
 */
export function sanitizeProductJsonForAi(
  product: Record<string, unknown>,
): Record<string, unknown> {
  const cleaned = cleanValue(product);
  return cleaned && typeof cleaned === "object" && !Array.isArray(cleaned)
    ? (cleaned as Record<string, unknown>)
    : {};
}
